parameters:
#    bluw_user.example.class: Bluw\UserBundle\Example

services:
#    bluw_user.example:
#        class: %bluw_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
